name: Testbuild for Linux (x86_64)
run-name: testbuild_linux_x86_64
on:
  push:
    branches:
      - 'master'
  pull_request:
    types:
      - edited
      - opened
      - synchronize
concurrency:
  # Cancel concurrent workflows for the same PR or commit hash.
  group: ${{github.workflow}}-${{github.event_name == 'pull_request' && github.head_ref || github.sha}}
  cancel-in-progress: true
jobs:
  build_ubuntu_x84_64:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - env: ubuntu
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Build
      run: |
        # Public runners come with 4 CPUs.
        make -j4
    - name: Create testbuild package
      run: |
        # Create release directory tree
        mkdir -p publish/quake2-xatrix-linux_x86_64-${{github.sha}}/misc/docs
        # Copy release assets
        cp -r release/* publish/quake2-xatrix-linux_x86_64-${{github.sha}}/
        # Copy misc assets
        cp -r stuff/mapfixes publish/quake2-xatrix-linux_x86_64-${{github.sha}}/misc
        cp LICENSE publish/quake2-xatrix-linux_x86_64-${{github.sha}}/misc/docs/LICENSE.txt
        cp README.md publish/quake2-xatrix-linux_x86_64-${{github.sha}}/misc/docs/README.txt
    - name: Upload testbuild package
      uses: actions/upload-artifact@v4
      with:
        name: quake2-xatrix-linux_x86_64-${{github.sha}}
        path: publish/
        if-no-files-found: error
